const START_GAME = "START_GAME";
const NEW_GAME = "NEW_GAME";
const END_TURN = "END_TURN";
const BUY_PROPERTY = "BUY_PROPERTY";
const ROLL_DICE = "ROLL_DICE";
const TRADE = "TRADE";
const MOVE_PLAYER = "MOVE_PLAYER";
const CHANGE_GAME_STATE = "CHANGE_GAME_STATE";

export default {
    START_GAME,
    NEW_GAME,
    END_TURN,
    BUY_PROPERTY,
    ROLL_DICE,
    TRADE,
    MOVE_PLAYER,
    CHANGE_GAME_STATE
};