const START_GAME = "START_GAME";
const NEW_GAME = "NEW_GAME";
const END_TURN = "END_TURN";
const ROLL_DICE = "ROLL_DICE";
const TRADE = "TRADE";
const MOVE_PLAYER = "MOVE_PLAYER";
const CHANGE_GAME_STATE = "CHANGE_GAME_STATE";
const UPDATE_CARD = "UPDATE_CARD";
const UPDATE_PLAYERS = "UPDATE_PLAYERS";
const BUY_OR_SELL = "BUY_OR_SELL";
const DOUBLE_DICE = "DOUBLE_DICE";
const RESET_DOUBLE_DICE = "RESET_DOUBLE_DICE";
const UPDATE_DISPLAY = "UPDATE_DISPLAY";
const RESET_DICE = "RESET_DICE";
const UPDATE_MENU = "UPDATE_MENU";
const UPDATE_FREE_PARKING = "UPDATE_FREE_PARKING";
const UPDATE_TRADE_ITEMS = "UPDATE_TRADE_ITEMS";
const SET_TRADE_PLAYER = "SET_TRADE_PLAYER";
const END_GAME = "END_GAME";

export default {
    START_GAME,
    NEW_GAME,
    END_TURN,
    ROLL_DICE,
    TRADE,
    MOVE_PLAYER,
    CHANGE_GAME_STATE,
    UPDATE_CARD,
    UPDATE_PLAYERS,
    BUY_OR_SELL,
    DOUBLE_DICE,
    RESET_DOUBLE_DICE,
    UPDATE_DISPLAY,
    RESET_DICE,
    UPDATE_MENU,
    UPDATE_FREE_PARKING,
    UPDATE_TRADE_ITEMS,
    SET_TRADE_PLAYER,
    END_GAME
};