const CHOOSING_ACTION = "CHOOSING_ACTION";
const ROLLING_DICE = "ROLLING_DICE";
const TRADING = "TRADING";
const ON_OWNED_PROPERTY = "ON_OWNED_PROPERTY";
const ON_OWN_PROPERTY = "ON_OWN_PROPERTY";
const ON_FREE_PROPERTY = "ON_FREE_PROPERTY";
const ON_CHANCE = "ON_CHANCE";
const ON_CHEST = "ON_CHEST";
const ON_TAX = "ON_TAX";
const END_OF_TURN = "END_OF_TURN";
const IN_JAIL_FIRST_TURN = "IN_JAIL_FIRST_TURN";
const IN_JAIL_BAIL_TURN = "IN_JAIL_BAIL_TURN";

export default {
    CHOOSING_ACTION,
    ROLLING_DICE,
    TRADING,
    ON_CHANCE,
    ON_CHEST,
    ON_FREE_PROPERTY,
    ON_OWNED_PROPERTY,
    ON_OWN_PROPERTY,
    ON_TAX,
    END_OF_TURN,
    IN_JAIL_FIRST_TURN,
    IN_JAIL_BAIL_TURN
}