const CHOOSING_ACTION = "CHOOSING_ACTION";
const ROLLING_DICE = "ROLLING_DICE";
const TRADING = "TRADING";
const DICE_ROLLED = "DICE_ROLLED";

export default {
    CHOOSING_ACTION,
    ROLLING_DICE,
    TRADING,
    DICE_ROLLED
}